### ISSUE TITLE
DLL 'BetterArtisanGoodIcons.dll' doesn't exist.

### ISSUE THREAD

**Issue by Peanutjammy** [chsiao58/EvenBetterArtisanGoodIcons#2]
I hope this message finds you well! 
Smapi tells me that it skipped the mod, due to "Even Better Artisan Good Icons 1.6.1 because its DLL 'BetterArtisanGoodIcons.dll' doesn't exist."
I downloaded the Harmony mod and also replaced the unique ID for Cat's mod as instructed, but it then told me that there were duplicates of the mod, and had to delete one.
After I deleted Cat's mod, it gave the repeating message that the DLL doesn't exist. I'm very lost now, and I'm unsure how to get it working.

Thank you for reading, and please have a lovely day!

**Comment by chsiao58** [comment]
Thanks for the report! That happened because I forgot to update the Entry DLL name... this will be fix on next update when I upload the mod to Nexus.

**Comment by chsiao58** [comment]
I have updated the mod for download, could you delete the whole original folder and try again? If it's working I will close this issue.

https://www.nexusmods.com/stardewvalley/mods/22144?tab=description
