### ISSUE TITLE
Even Better Artisan Goods Not workign with a content pack

### ISSUE THREAD

**Issue by MidnightChord** [chsiao58/EvenBetterArtisanGoodIcons#3]
Here is my Eroro log: https://smapi.io/log/6cb5357c879d4a3fa07dcffae7d7971e

This is what i get when i try to run my Stardew Valley Expanded Content Pack for EBAGI
i have updated the UniqueID but still get the same problem, i dotn get this problem if i remove my pack and only use EBAGI

Any idea whats happening?

**Comment by chsiao58** [comment]
Thanks for the report! I had an inkling my the current status of mod is going to run into bug when it comes to additional crop added by other mod, I will look into this as soon as I can.

**Comment by MidnightChord** [comment]
I just tested my Stardew Valley Expanded content pack with the most recent version on nexus and it seems to be workign fine now

**Comment by MidnightChord** [comment]
Only thign that isnt working is th elittle Icon up in the Corner

**Comment by chsiao58** [comment]
That's good to hear. I will be testing that out later myself and see how I should fix that issue.

**Comment by chsiao58** [comment]
Hey, from your experience, has the corner icon for expansion crops always been working in 1.5 with original BAGI?

**Comment by MidnightChord** [comment]
Yeah it worked fine in Original BAGI

**Comment by MidnightChord** [comment]
But now when I turned it on it only showed like a grass thing for all of the SVE ones

**Comment by chsiao58** [comment]
Turned out the fix is fairly easy. I have uploaded version 1.6.4 that fix this issue. Could you please verify for me just to be sure?

**Comment by MidnightChord** [comment]
Will do as soon as I have time:3

**Comment by MidnightChord** [comment]
It worked perfectly now:3
