### ISSUE TITLE
Conflict with Machine Progression System (https://www.nexusmods.com/stardewvalley/mods/21720)

### ISSUE THREAD

**Issue by MizukiHikari** [chsiao58/EvenBetterArtisanGoodIcons#4]
So when using EBAGI and MPS, the texture of machine that has finished their products changes to something else entirely.. Is there a way to add compatibility between your mod and MPS..?

[Pic Attached](https://i.postimg.cc/mZ3RDv33/Capture.png)

UP = Finished Machine
DOWN = Machine when Processing Product

**Comment by MizukiHikari** [comment]
Sure, i can give you two examples with EBAGI and without EBAGI enabled..

EBAGI disabled
[pic](https://i.postimg.cc/0NvRpngt/image.png)
[smapi log](https://smapi.io/log/dcc230309a2a49b7a3e1ff1ba7d3fdcf)

EBAGI enabled
[pic](https://i.postimg.cc/4dJ1b7xk/image.png)
[smapi log](https://smapi.io/log/503fcf3b67704e678774b8046cf04295)

Ignore the PFM warning, that because i thinned the modlist so i don't install more crops mods etc..
Thanks.

**Comment by chsiao58** [comment]
Thanks for the log, I will look into this when I got some time.

**Comment by chsiao58** [comment]
I finally had some time to look into this. Sorry it took so long! The issue should be fixed now with the latest version of EBAGI. Please verify if it works properly on your end.

**Comment by MizukiHikari** [comment]
Heya, thank you so much for your time to fix this.. I have checked it, and yep it works properly now.. Thank you again!! 😄 

[Fixed](https://i.postimg.cc/0Q6xTyGt/06052024.png)
